language: python
python:
  - "2.7"
install:
  - pip install coveralls
before_script:
  - mkdir -p google/appengine/api
  - touch google/__init__.py && touch google/appengine/__init__.py 
  - cp utils/tests/fake_appengine_memcache.py google/appengine/api/__init__.py
script:
  nosetests --with-coverage --cover-package=utils
after_success:
  coveralls
